/*
 * This source file was generated by the Gradle 'init' task
 */
package org.atu.stocklib;

/**
 * A Java class for the stockLib library
 */
public class StockLib {


    /**
     * A simple dummy java library created using Gradle
     *
     * @return true
     */
    public boolean someLibraryMethod() {
        return true;
    }
}
