/*
 * This source file was generated by the Gradle 'init' task
 */
package org.atu.stocklib;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        StockLib classUnderTest = new StockLib();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
